from utils.db import db,ma


class SEF_TSESSION(db.Model):

    SESN_ID_TANDA = db.Column(db.Integer,primary_key=True)
    SESD_FECHA_INICIO = db.Column(db.Date)
    SESD_FECHA_FIN = db.Column(db.Date)
    SESV_CALIBRADOR = db.Column(db.String(50))  
    SESN_TEMPERATURA = db.Column(db.Float)
    EQUN_ID_EPM = db.Column(db.Integer)
    SESV_TIPO_DE_ENERGIA = db.Column(db.String(20))
    SESV_FLUJO_ENERGIA = db.Column(db.String(20))
    SESN_TENSION_PRUEBA = db.Column(db.Float) 
    SESN_CORRIENTE_PRUEBA_NOM = db.Column(db.Float) 
    SESN_CORRIENTE_PRUEBA_MAX = db.Column(db.Float)
    SESV_METODO_FUNCIONAMIENTO_SC = db.Column(db.Float)
    SESV_METODO_ARRANQUE = db.Column(db.Float)
    SESV_METODO_EXACTITUD = db.Column(db.Float)
    SESV_METODO_VERIFICACION_CONST = db.Column(db.Float)


    def __init__(self,SESN_ID_TANDA,SESD_FECHA_INICIO,SESD_FECHA_FIN,SESV_CALIBRADOR,SESN_TEMPERATURA,EQUN_ID_EPM,SESV_TIPO_DE_ENERGIA,SESV_FLUJO_ENERGIA,SESN_TENSION_PRUEBA,SESN_CORRIENTE_PRUEBA_NOM,SESN_CORRIENTE_PRUEBA_MAX,SESV_METODO_FUNCIONAMIENTO_SC,SESV_METODO_ARRANQUE,SESV_METODO_EXACTITUD,SESV_METODO_VERIFICACION_CONST):
        self.SESN_ID_TANDA = SESN_ID_TANDA
        self.SESD_FECHA_INICIO = SESD_FECHA_INICIO
        self.SESD_FECHA_FIN = SESD_FECHA_FIN
        self.SESV_CALIBRADOR = SESV_CALIBRADOR
        self.SESN_TEMPERATURA = SESN_TEMPERATURA
        self.EQUN_ID_EPM = EQUN_ID_EPM
        self.SESV_TIPO_DE_ENERGIA = SESV_TIPO_DE_ENERGIA
        self.SESV_FLUJO_ENERGIA = SESV_FLUJO_ENERGIA
        self.SESN_TENSION_PRUEBA = SESN_TENSION_PRUEBA
        self.SESN_CORRIENTE_PRUEBA_NOM = SESN_CORRIENTE_PRUEBA_NOM
        self.SESN_CORRIENTE_PRUEBA_MAX = SESN_CORRIENTE_PRUEBA_MAX
        self.SESV_METODO_FUNCIONAMIENTO_SC = SESV_METODO_FUNCIONAMIENTO_SC
        self.SESV_METODO_ARRANQUE = SESV_METODO_ARRANQUE
        self.SESV_METODO_EXACTITUD = SESV_METODO_EXACTITUD
        self.SESV_METODO_VERIFICACION_CONST = SESV_METODO_VERIFICACION_CONST

class SesionSchema(ma.Schema):
    class Meta:
        fields = ('SESN_ID_TANDA','SESD_FECHA_INICIO','SESD_FECHA_FIN','SESV_CALIBRADOR','SESN_TEMPERATURA','EQUN_ID_EPM','SESV_TIPO_DE_ENERGIA','SESV_FLUJO_ENERGIA','SESN_TENSION_PRUEBA','SESN_CORRIENTE_PRUEBA_NOM','SESN_CORRIENTE_PRUEBA_MAX','SESV_METODO_FUNCIONAMIENTO_SC','SESV_METODO_ARRANQUE','SESV_METODO_EXACTITUD','SESV_METODO_VERIFICACION_CONST')

sesion_schema = SesionSchema()
sesions_schema = SesionSchema(many=True)